"""disappearing messages, chat color, contact notes

Revision ID: 4a8acf83c689
Revises: 63169d187c8d
Create Date: 2026-07-11 15:08:22.574478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8acf83c689'
down_revision: Union[str, Sequence[str], None] = '63169d187c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'target_user_id', name='uq_contact_note_owner_target')
    )
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_color', sa.String(), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disappearing_seconds', sa.Integer(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('disappearing_seconds')

    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.drop_column('chat_color')

    op.drop_table('contact_notes')
    # ### end Alembic commands ###
